version: '3.8'

services:
  medidefend_backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      POSTGRES_USER: medidefenduser
      POSTGRES_PASSWORD: S3YKe9y7LDmN%xV3@6AU82!Tvk
      POSTGRES_DB: medidefend
      POSTGRES_HOST: postgres
      ENVIRONMENT: PROD # oder DEV f√ºr die Entwicklungsumgebung
    networks:
      - platform_network
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: medidefenduser
      POSTGRES_PASSWORD: S3YKe9y7LDmN%xV3@6AU82!Tvk
      POSTGRES_DB: medidefend
    volumes:
      - md_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - platform_network

volumes:
  md_data:

networks:
  platform_network:
    external: true
